# Use a lightweight OpenJDK image
FROM bellsoft/liberica-openjdk-alpine:21

# Set working directory inside the container
WORKDIR /app

# Copy the JAR file into the container
COPY target/financeiroapi.jar /app/financeiroapi.jar

# Expose the application port
EXPOSE 8080

ENV PSQL_IP=postgres-container
ENV PSQL_PORT=5432

# Command to run the application
CMD ["java", "-XX:+UseContainerSupport", "-Xmx512m", "-jar", "/app/financeiroapi.jar"]